"""Dashboard aggregation — reads terminal candidate JSONs from disk and
computes funnel / completion / drop-off / throughput metrics on demand.

Pure functions (no FastAPI imports) so they're trivially unit-testable and
can later be reused by a CLI or notebook without booting the API.
"""

from __future__ import annotations

from collections import Counter
from datetime import date
from pathlib import Path
from typing import Optional

from pydantic import BaseModel, Field

from .config import settings
from .models import ConversationState, Stage


# Generated by GitHub Copilot
# Canonical 7-question flow from README — used for both drop-off ordering
# and funnel computation. Keep in sync with the graph routing.
_FUNNEL_STAGES: tuple[Stage, ...] = (
    Stage.ASK_NAME,
    Stage.ASK_LICENSE,
    Stage.ASK_CITY,
    Stage.ASK_AVAILABILITY,
    Stage.ASK_SCHEDULE,
    Stage.ASK_EXPERIENCE,
    Stage.ASK_START_DATE,
)

_TERMINAL_SUBDIRS: tuple[str, ...] = ("qualified", "disqualified", "abandoned")


class FunnelStep(BaseModel):
    stage: str
    reached: int


class ThroughputBucket(BaseModel):
    date: str  # YYYY-MM-DD (UTC)
    count: int


class DurationStats(BaseModel):
    overall_seconds: Optional[float] = None
    by_status: dict[str, Optional[float]] = Field(default_factory=dict)


class DashboardMetrics(BaseModel):
    job_id: Optional[str] = None
    totals: dict[str, int] = Field(default_factory=dict)
    completion_rate: float = 0.0
    drop_off_by_stage: dict[str, int] = Field(default_factory=dict)
    duration_seconds: DurationStats = Field(default_factory=DurationStats)
    disqualification_reasons: dict[str, int] = Field(default_factory=dict)
    funnel: list[FunnelStep] = Field(default_factory=list)
    message_source_ratio: dict[str, int] = Field(default_factory=dict)
    throughput: list[ThroughputBucket] = Field(default_factory=list)


def load_candidates(job_id: Optional[str] = None) -> list[ConversationState]:
    """Walk data/candidates/<status>/*.json and return parsed states.

    Malformed files are skipped silently — the dashboard must never 500 on a
    single bad record. `job_id=None` returns everything.
    """
    root = settings.data_dir / "candidates"
    if not root.exists():
        return []
    out: list[ConversationState] = []
    for sub in _TERMINAL_SUBDIRS:
        sub_dir = root / sub
        if not sub_dir.is_dir():
            continue
        for path in sorted(sub_dir.glob("*.json")):
            state = _safe_load(path)
            if state is None:
                continue
            if job_id is not None and state.job_id != job_id:
                continue
            out.append(state)
    return out


def _safe_load(path: Path) -> Optional[ConversationState]:
    """Parse one candidate file; return None on any failure."""
    try:
        return ConversationState.model_validate_json(path.read_text(encoding="utf-8"))
    except Exception:  # noqa: BLE001 — defensive: corrupt file shouldn't break dashboard
        return None


def _stage_index(stage: Stage) -> int:
    """Position in the 7-step funnel; -1 if not an ASK_* stage."""
    try:
        return _FUNNEL_STAGES.index(stage)
    except ValueError:
        return -1


def _max_stage_index_reached(state: ConversationState) -> int:
    """Highest funnel-stage index this conversation got to.

    QUALIFIED ⇒ all 7 stages cleared. For terminal non-qualified states the
    `current_stage` is the stage they were on when the flow ended — they did
    answer all earlier stages, so they count as reached.
    """
    if state.qualification_status == "qualified":
        return len(_FUNNEL_STAGES) - 1
    return _stage_index(state.current_stage)


def _avg_or_none(values: list[float]) -> Optional[float]:
    return round(sum(values) / len(values), 2) if values else None


def compute_metrics(
    states: list[ConversationState],
    job_id: Optional[str] = None,
) -> DashboardMetrics:
    """Aggregate a list of terminal conversations into dashboard metrics.

    Empty input returns a zeroed `DashboardMetrics` (no divide-by-zero, safe
    for the empty-dataset HTML placeholder).
    """
    metrics = DashboardMetrics(job_id=job_id)

    # Totals per status (always include the three terminal buckets so callers
    # can render a stable schema even when one is empty).
    status_counter: Counter[str] = Counter(s.qualification_status for s in states)
    totals = {k: status_counter.get(k, 0) for k in _TERMINAL_SUBDIRS}
    totals["total"] = sum(totals.values())
    metrics.totals = totals

    if not states:
        metrics.funnel = [FunnelStep(stage=s.value, reached=0) for s in _FUNNEL_STAGES]
        metrics.drop_off_by_stage = {s.value: 0 for s in _FUNNEL_STAGES}
        metrics.message_source_ratio = {"llm": 0, "template": 0, "unknown": 0}
        return metrics

    # Completion rate.
    metrics.completion_rate = round(totals["qualified"] / totals["total"], 4)

    # Drop-off by stage — only non-qualified conversations, bucketed by their
    # final stage. Missing stages still appear with a zero count for a stable
    # bar chart.
    drop_off = {s.value: 0 for s in _FUNNEL_STAGES}
    for s in states:
        if s.qualification_status == "qualified":
            continue
        if s.current_stage in _FUNNEL_STAGES:
            drop_off[s.current_stage.value] += 1
    metrics.drop_off_by_stage = drop_off

    # Durations (seconds): overall and per status; null when no `ended_at`.
    durations_by_status: dict[str, list[float]] = {k: [] for k in _TERMINAL_SUBDIRS}
    all_durations: list[float] = []
    for s in states:
        if s.ended_at is None or s.started_at is None:
            continue
        secs = (s.ended_at - s.started_at).total_seconds()
        if secs < 0:  # corrupt timestamps — skip rather than skew the mean
            continue
        all_durations.append(secs)
        durations_by_status.setdefault(s.qualification_status, []).append(secs)
    metrics.duration_seconds = DurationStats(
        overall_seconds=_avg_or_none(all_durations),
        by_status={k: _avg_or_none(v) for k, v in durations_by_status.items()},
    )

    # Disqualification reasons (only over disqualified records).
    reasons = Counter(
        s.disqualification_reason
        for s in states
        if s.qualification_status == "disqualified" and s.disqualification_reason
    )
    metrics.disqualification_reasons = dict(reasons)

    # Funnel — "reached stage X" = max_stage_index_reached >= X.
    funnel: list[FunnelStep] = []
    for idx, stage in enumerate(_FUNNEL_STAGES):
        reached = sum(1 for s in states if _max_stage_index_reached(s) >= idx)
        funnel.append(FunnelStep(stage=stage.value, reached=reached))
    metrics.funnel = funnel

    # Message-source ratio across all agent turns.
    src = Counter()
    for s in states:
        for turn in s.transcript:
            if turn.role != "agent":
                continue
            src[turn.source or "unknown"] += 1
    metrics.message_source_ratio = {
        "llm": src.get("llm", 0),
        "template": src.get("template", 0),
        "unknown": src.get("unknown", 0),
    }

    # Throughput — daily buckets keyed by started_at (UTC).
    by_day: Counter[date] = Counter()
    for s in states:
        if s.started_at is None:
            continue
        by_day[s.started_at.date()] += 1
    metrics.throughput = [
        ThroughputBucket(date=d.isoformat(), count=c)
        for d, c in sorted(by_day.items())
    ]

    return metrics


def get_dashboard_metrics(job_id: Optional[str] = None) -> DashboardMetrics:
    """Convenience: load + compute in one call. Used by the HTTP layer."""
    return compute_metrics(load_candidates(job_id), job_id=job_id)
