import uuid
from datetime import datetime
from enum import Enum
from typing import Literal, Optional

from pydantic import BaseModel, Field


class Stage(str, Enum):
    GREETING = "greeting"
    ASK_NAME = "ask_name"
    ASK_LICENSE = "ask_license"
    ASK_CITY = "ask_city"
    ASK_AVAILABILITY = "ask_availability"
    ASK_SCHEDULE = "ask_schedule"
    ASK_EXPERIENCE = "ask_experience"
    ASK_START_DATE = "ask_start_date"
    QUALIFIED = "qualified"
    DISQUALIFIED = "disqualified"
    ABANDONED = "abandoned"


Availability = Literal["full_time", "part_time", "weekends"]
ScheduleSlot = Literal["morning", "afternoon", "evening", "flexible"]
Sentiment = Literal["positive", "neutral", "frustrated", "confused"]
Language = Literal["es", "en"]
QualificationStatus = Literal["in_progress", "qualified", "disqualified", "abandoned"]
DisqualificationReason = Literal["no_license", "outside_service_area", "no_availability"]


class CandidateRecord(BaseModel):
    full_name: Optional[str] = None
    drivers_license: Optional[bool] = None
    city_zone: Optional[str] = None
    availability: list[Availability] = Field(default_factory=list)
    preferred_schedule: list[ScheduleSlot] = Field(default_factory=list)
    experience_years: Optional[int] = None
    experience_platforms: list[str] = Field(default_factory=list)
    start_date: Optional[str] = None


MessageSource = Literal["llm", "template"]


class Turn(BaseModel):
    role: Literal["agent", "user"]
    text: str
    ts: datetime = Field(default_factory=datetime.utcnow)
    sentiment: Optional[Sentiment] = None
    # For agent turns: "llm" if generated by the LLM, "template" if produced by
    # deterministic fallback (greeting, terminal closings, stage-question
    # templates). None for user turns or legacy data.
    source: Optional[MessageSource] = None


class SentimentSummary(BaseModel):
    overall: Sentiment = "neutral"
    per_turn: list[dict] = Field(default_factory=list)


class ConversationState(BaseModel):
    conversation_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    started_at: datetime = Field(default_factory=datetime.utcnow)
    ended_at: Optional[datetime] = None

    language: Language = "es"
    current_stage: Stage = Stage.GREETING

    candidate: CandidateRecord = Field(default_factory=CandidateRecord)
    transcript: list[Turn] = Field(default_factory=list)
    reask_counts: dict[str, int] = Field(default_factory=dict)
    last_user_ts: Optional[datetime] = None

    qualification_status: QualificationStatus = "in_progress"
    disqualification_reason: Optional[DisqualificationReason] = None

    sentiment: SentimentSummary = Field(default_factory=SentimentSummary)

    job_id: str = "delivery_driver"
    metadata: dict = Field(default_factory=dict)
